name       : libu2f-host
version    : 1.1.6
release    : 7
source     :
    - https://github.com/Yubico/libu2f-host/archive/libu2f-host-1.1.6.tar.gz : 45beabd3ba5a08643f3aea4642ea4c68f34f0ad701878f3ad447c5b3c13ecb21
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Yubico Universal 2nd Factor (U2F) Host C Library
description: |
    Libu2f-host provides a C library and command-line tool that implements the host-side of the U2F protocol. There are APIs to talk to a U2F device and perform the U2F Register and U2F Authenticate operations.
builddeps  :
    - pkgconfig(hidapi-hidraw)
    - pkgconfig(json-c)
    - gengetopt
    - help2man
setup      : |
    %reconfigure --disable-static --with-udevrulesdir=%libdir%/udev/rules.d/
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
