name       : libu2f-host
version    : 1.1.3
release    : 1
source     :
    - https://github.com/Yubico/libu2f-host/archive/libu2f-host-1.1.3.tar.gz : 2e43679655bbfe3bb1dfee16bb6c2a324d22c7907071a8703f5195eafe891e27
license    : GPL-3.0
component  : programming
summary    : Yubico Universal 2nd Factor (U2F) Host C Library
description: |
    Yubico Universal 2nd Factor (U2F) Host C Library
builddeps  :
    - pkgconfig(hidapi-hidraw)
    - pkgconfig(json-c)
    - gengetopt
    - help2man
setup      : |
    %reconfigure --disable-static --with-udevrulesdir=%libdir%/udev/rules.d/
build      : |
    %make
install    : |
    %make_install
