name       : libu2f-host
version    : 1.1.9
release    : 8
source     :
    - https://github.com/Yubico/libu2f-host/archive/libu2f-host-1.1.9.tar.gz : f2d9ac7d0bb448d213a81aa3c2e97ae48b277144040c74b5c4f33d871338e93c
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Yubico Universal 2nd Factor (U2F) Host C Library
description: |
    Libu2f-host provides a C library and command-line tool that implements the host-side of the U2F protocol. There are APIs to talk to a U2F device and perform the U2F Register and U2F Authenticate operations.
builddeps  :
    - pkgconfig(hidapi-hidraw)
    - pkgconfig(json-c)
    - gengetopt
    - help2man
setup      : |
    %reconfigure --disable-static --with-udevrulesdir=%libdir%/udev/rules.d/
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
